### ISSUE TITLE
watch中に素早く保存を繰り返すと落ちる

### ISSUE THREAD

**Issue by pvcresin** [Paperist/issues#1]
**バグ・要望 (Bugs / Requests)**

`npm run watch`して，`index.md`で保存を素早く2回行うと，`.paperist/main.pdf main.pdf`が無いと怒られる．
（前の生成が走っている最中のため？）

----------

**投稿前に以下の項目を確認してください**
**Please check below before reporting.**

- [x] すでに同じ報告がないか確認してください (Please check if the issue has NOT been reported yet. )
 - See https://github.com/Paperist/issues/issues.

**Comment by 3846masa** [comment]
https://github.com/Paperist/cli によって修正された
