### ISSUE TITLE
ビルドが完了したときのメッセージが欲しい

### ISSUE THREAD

**Issue by pvcresin** [Paperist/issues#2]
**バグ・要望 (Bugs / Requests)**

ビルド時はめちゃくちゃログが出るので，ちゃんと終わったことを確認するためにも完了メッセージを表示してほしい．

----------

**投稿前に以下の項目を確認してください**
**Please check below before reporting.**

- [x] すでに同じ報告がないか確認してください (Please check if the issue has NOT been reported yet. )
 - See https://github.com/Paperist/issues/issues.

**Comment by 3846masa** [comment]
https://github.com/Paperist/cli によって修正された
