### ISSUE TITLE
パッケージをinstallしたりremoveしたりしていると，remark-beheadがないと怒られる

### ISSUE THREAD

**Issue by pvcresin** [Paperist/issues#4]
**バグ・要望 (Bugs / Requests)**

タイトル通り．
テンプレートをpackage.jsonのdependenciesに追記したら直る疑惑？（本人談）

----------

**投稿前に以下の項目を確認してください**
**Please check below before reporting.**

- [x] すでに同じ報告がないか確認してください (Please check if the issue has NOT been reported yet. )
 - See https://github.com/Paperist/issues/issues.

**Comment by 3846masa** [comment]
https://github.com/Paperist/cli によって修正された
