### ISSUE TITLE
CLIが動かない

### ISSUE THREAD

**Issue by pvcresin** [Paperist/issues#8]
**バグ・要望 (Bugs / Requests)**

CLIが動かない．というか無い．

----------

**投稿前に以下の項目を確認してください**
**Please check below before reporting.**

- [x] すでに同じ報告がないか確認してください (Please check if the issue has NOT been reported yet. )
 - See https://github.com/Paperist/issues/issues.

**Comment by 3846masa** [comment]
https://github.com/Paperist/cli ができた
