### ISSUE TITLE
タイトルのフォントが違う

### ISSUE THREAD

**Issue by pvcresin** [Paperist/issues#9]
**バグ・要望 (Bugs / Requests)**

タイトルのフォントが違うんですけど～～！！

----------

**投稿前に以下の項目を確認してください**
**Please check below before reporting.**

- [x] すでに同じ報告がないか確認してください (Please check if the issue has NOT been reported yet. )
 - See https://github.com/Paperist/issues/issues.

**Comment by 3846masa** [comment]
Fixed on https://github.com/Paperist/template-ipsj-techreport/commit/482cf2abbbc8aced66e8edcd5120c559353d15ae
